In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("air_quality_health.csv")
df.head()

,PM2_5,PM10,NO2,SO2,O3,Temperature,Humidity,WindSpeed,AQI,HealthImpactScore
0,115.489335,82.201842,56.032608,67.924893,147.279011,23.777243,68.619272,0.946194,97.0,19.4
1,285.460720,221.341369,53.160866,80.074777,203.303759,26.570248,32.928977,2.647884,206.0,41.2
2,220.938213,350.448876,181.719643,26.545854,192.438623,39.909159,85.429592,10.059327,225.0,45.0
3,181.604253,295.567706,53.661509,63.237662,46.935977,21.900154,65.983718,9.317836,166.0,33.2
4,51.025499,324.558848,58.030197,58.031106,45.819873,40.437739,31.790291,4.532391,121.0,24.2

In [4]:
df.columns

Index(['PM2_5', 'PM10', 'NO2', 'SO2', 'O3', 'Temperature', 'Humidity',
       'WindSpeed', 'AQI', 'HealthImpactScore'],
      dtype='object')

In [5]:
df.shape

(13000, 10)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PM2_5              13000 non-null  float64
 1   PM10               13000 non-null  float64
 2   NO2                13000 non-null  float64
 3   SO2                13000 non-null  float64
 4   O3                 13000 non-null  float64
 5   Temperature        13000 non-null  float64
 6   Humidity           13000 non-null  float64
 7   WindSpeed          13000 non-null  float64
 8   AQI                13000 non-null  float64
 9   HealthImpactScore  13000 non-null  float64
dtypes: float64(10)
memory usage: 1015.8 KB

In [7]:
df.isnull().sum()

PM2_5                0
PM10                 0
NO2                  0
SO2                  0
O3                   0
Temperature          0
Humidity             0
WindSpeed            0
AQI                  0
HealthImpactScore    0
dtype: int64

In [8]:
# AQI-related features
features = ['PM2_5', 'PM10', 'NO2', 'SO2', 'O3', 'Temperature', 'Humidity', 'WindSpeed']
x = df[features]
y = df['AQI']
# Target for Health Impact
y_health = df['HealthImpactScore']

In [9]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\daram\onedrive\desktop\final year main project [aqi]\project\lowkya\lib\site-packages (from scikit-learn) (3.6.0)

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, y_health_train, y_health_test = train_test_split(x, y, y_health, test_size=0.2, random_state=38)

In [11]:
# Train AQI model
from sklearn.ensemble import RandomForestRegressor
rf_aqi = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf_aqi.fit(x_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [12]:
# Predict
predicted_aqi = rf_aqi.predict(x_test)

In [13]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np
print("AQI Model Performance:")
print("MSE:", mean_squared_error(y_test, predicted_aqi))
print("RMSE:", np.sqrt(mean_squared_error(y_test, predicted_aqi)))
print("MAE:", mean_absolute_error(y_test, predicted_aqi))
print("R2 Score:", r2_score(y_test, predicted_aqi))

AQI Model Performance:
MSE: 17.150635475961536
RMSE: 4.141332572489383
MAE: 3.261202884615384
R2 Score: 0.99176770224699

In [23]:
import joblib

joblib.dump(rf_aqi, "aqi.pkl")

['aqi.pkl']

In [24]:
import pandas as pd

x_health = pd.DataFrame({
    'PM2_5': x_test['PM2_5'],
    'PM10': x_test['PM10'],
    'NO2': x_test['NO2'],
    'SO2': x_test['SO2'],
    'O3': x_test['O3'],
    'Temperature': x_test['Temperature'],
    'Humidity': x_test['Humidity'],
    'Wind_Speed': x_test['WindSpeed'],
        'Predicted_AQI': predicted_aqi
})
y_health = y_health_test

In [25]:
## Scale Health Impact features
from sklearn.preprocessing import StandardScaler
scaler_health = StandardScaler()
x_health_scaled = scaler_health.fit_transform(x_health)

In [34]:
## Train Health Impact Model
rf_health = RandomForestRegressor(n_estimators=100, random_state=38)
rf_health.fit(x_health_scaled, y_health)

RandomForestRegressor(random_state=38)

In [27]:
# Predict
yh_pred = rf_health.predict(x_health_scaled)

In [28]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np
print("Health Impact Model Performance:")
print("MSE:", mean_squared_error(y_health, yh_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_health, yh_pred)))
print("MAE:", mean_absolute_error(y_health, yh_pred))
print("R2 Score:", r2_score(y_health, yh_pred))

Health Impact Model Performance:
MSE: 0.049276655384615425
RMSE: 0.22198345745711645
MAE: 0.17319692307692314
R2 Score: 0.9993853838688836

In [31]:
joblib.dump(rf_health, "health.pkl")
joblib.dump(scaler_health, "health_scaler_model.pkl")

['health_scaler_model.pkl']

In [32]:
aqi_feature_importance = rf_aqi.feature_importances_

feature_importance_df = pd.DataFrame({
    "Environmental_Parameter": x.columns,
    "Importance_Score": aqi_feature_importance
}).sort_values(by="Importance_Score", ascending=False)

feature_importance_df

  Environmental_Parameter  Importance_Score
0                   PM2_5          0.562409
1                    PM10          0.379042
2                     NO2          0.033145
4                      O3          0.019628
3                     SO2          0.002619
6                Humidity          0.001072
7               WindSpeed          0.001043
5             Temperature          0.001042

In [33]:
top_contributors = feature_importance_df.head(3)

top_contributors

  Environmental_Parameter  Importance_Score
0                   PM2_5          0.562409
1                    PM10          0.379042
2                     NO2          0.033145